apps/box/src/components/Cards/ColorSettingsCard.tsx
libs/component-library/src/lib/theme/theme.ts

Added a selected style to the LED color settings dots

---

apps/box/src/app/App.tsx

Fixes issue with bottom sheet backdrop on Android where pressing
the backdrop would not close the modal as expected.

Fix issue with bottom sheet backdrop

---

libs/component-library/src/lib/bottom-sheet/bottomSheetModal.tsx

Fixes issue where bottom sheet would not return to prior position
after dismissing the keyboard.

Fix interaction between bottom sheet & keyboard

---

libs/component-library/src/lib/theme/inputClasses.ts
libs/component-library/src/lib/theme/theme.ts

There are some platform differences with how text input components
align their text. This update updates alignment to be consistent on both
platforms.

Fix alignment issues with Text Inputs

---

apps/box/src/components/Text.tsx
libs/component-library/src/index.ts
libs/component-library/src/lib/text/text.tsx
libs/component-library/src/lib/theme/theme.ts

Added generic reusable text comps
- closes #109

- Added reusable Text comps to Box app

---

README.md
package.json

Adds a couple convenience yarn scripts for building/running apps.

Add yarn scripts to launch apps

---

apps/box/ios/Podfile.lock
package.json
yarn.lock

- Updated to latest
- Added compatible with version

Updated async package to latest

---

apps/box/src/screens/InitialSetup/Welcome.screen.tsx

Update welcome screen buttons sizes

---

package.json
yarn.lock

Added state management package
Closes #132

Add Zustand state managment package

---

libs/component-library/src/lib/utils/conversions.ts

Added helper to comp library to capitalise the first letter of a word. This is useful for when using some piece of state as display text (For example light and dark mode)
- closes: #148

Add Capitalisation Helper to comp lib

---

libs/component-library/src/index.ts
libs/component-library/src/lib/switch/switch.tsx

Added Switch component to component library
- closes: #145
Dark:
Light:

Add Switch component to comp library

---

apps/box/src/constants/layout.ts

Adding layout functions to help scale dimensions by width or height based off Figama UI sizes
- Closes: #151

Add layout helpers

---

apps/box/src/components/Cards/ColorSettingsCard.tsx
apps/box/src/components/Cards/ConnectedDevicesCard.tsx
libs/component-library/src/lib/bottom-sheet/bottomSheetModal.tsx

Updates the bottom-sheet to add padding on the bottom to account for
safe areas.

Update bottom-sheet for safe area insets

---

apps/box/src/app/App.tsx
apps/box/src/screens/Box.screen.tsx
libs/component-library/src/lib/safe-area-box/safeAreaBox.tsx

Uses SafeAreaView from react-native-safe-area-context per recommendation
from React Navigation docs:
https://reactnavigation.org/docs/handling-safe-area/

Use SafeAreaView from react-native-safe-area-context

---

libs/component-library/src/lib/button/button.tsx

Added center icon to button comp
closes: #172

Add center icon to button

---

apps/box/src/app/App.tsx

This PR gets user preference mode from the store, select the correct theme based off the mode and pass it down through provider to all components
- Closes: #157

Add auto theme switching to app

---

apps/box/src/components/SettingsList/SettingsMenu.tsx
apps/box/src/navigation/ComponentGallery.navigator.tsx
apps/box/src/navigation/MainTabs.navigator.tsx
apps/box/src/navigation/navigationConfig.ts
apps/box/src/screens/Settings/ComponentGallery.screen.tsx
apps/box/src/screens/Settings/ComponentGallery/AvatarDemo.screen.tsx

Adds Component Gallery to settings menu.

Add Component Gallery

---

apps/box/src/components/Text.tsx

Adds Small Header text for modals and screens in blox app
Closes #190

Added reusable small header text comp

---

libs/component-library/src/lib/types.ts

- WithPartial - copy type and update with partial (optional) types
- RequireOnly - make all partial with specific required
Closes: #188

Add type helpers for:

---

libs/component-library/src/index.ts
libs/component-library/src/lib/header/header.tsx

This PR Adds the header component to the comp library
**Screenshots**
Light:
Dark: 
Closes #176

Add initial header comp

---

apps/box/src/components/Cards/ConnectedDevicesCard.tsx

Breaking out comp for empty card

Adding empty card comp

---

apps/box/src/navigation/ComponentGallery.navigator.tsx
apps/box/src/navigation/navigationConfig.ts
apps/box/src/screens/Settings/ComponentGallery.screen.tsx
apps/box/src/screens/Settings/ComponentGallery/AvatarDemo.screen.tsx
apps/box/src/screens/Settings/ComponentGallery/ButtonGroupDemo.screen.tsx
libs/component-library/src/index.ts
libs/component-library/src/lib/button-group/buttonGroup.tsx

Adds button group component to component library. 
Resolves #194 
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Button group implementation

---

apps/box/src/screens/Settings/ComponentGallery/TabsDemo.screen.tsx
libs/component-library/src/lib/tabs/tabs.tsx

Adds Auto Width Tabs component and updates the Tabs Demo screen.
Resolves #207 
https://user-images.githubusercontent.com/475007/186773620-1a5e78ba-0b13-416c-9ad3-ca57d8360e46.mov

Add Auto Width Tabs component

---

libs/component-library/src/lib/progress-bar/progressBar.tsx

Rewrites the Progress Bar component to use Reanimated to fix some
odd opacity issues on Android.

Rewrite Progress Bar to use Reanimated

---

libs/component-library/src/lib/toast/components/Toast.tsx

Added Panhandler to toast
https://user-images.githubusercontent.com/17250443/188504575-88706f88-5c80-4042-8121-c75d5f470589.mp4

Added panhandler to toast

---

.vscode/settings.json
apps/box/src/components/ProfileBottomSheet.tsx
apps/box/src/components/WalletDetails.tsx
apps/box/src/screens/Devices.screen.tsx
apps/box/src/screens/Users/UserHeader.tsx
apps/box/src/screens/Users/Users.screen.tsx
apps/box/src/utils/walletConnectConifg.ts

[Users screen show the current user #312](https://github.com/functionland/fx-components/issues/312)
[Devices screen correction #310](https://github.com/functionland/fx-components/issues/310)

Fixed issues

---

.gitignore
apps/box/src/app/App.tsx
package.json
yarn.lock

if app exited or closed unexpectedly, close datastoer

added listener to close datastore on app close

---

apps/box/package.json
apps/box/src/api/hub.ts
apps/box/src/api/wifi.ts
apps/box/src/components/Cards/ConnectedDevicesCard.tsx
apps/box/src/components/FlashingCircle.tsx
apps/box/src/components/FlashingTower.tsx
apps/box/src/components/index.ts
apps/box/src/models/blox.ts
apps/box/src/screens/Blox/Blox.screen.tsx
apps/box/src/screens/Blox/components/BloxInteraction.tsx
apps/box/src/screens/Devices.screen.tsx
apps/box/src/screens/InitialSetup/ConnectToBlox.screen.tsx
apps/box/src/screens/InitialSetup/LinkPassword.screen.tsx
apps/box/src/screens/InitialSetup/SetBloxAuthorizer.screen.tsx
apps/box/src/screens/InitialSetup/SetupComplete.screen.tsx
apps/box/src/stores/useBloxsStore.ts
apps/box/src/stores/useUserProfileStore.ts
package.json
yarn.lock

1- In Authorize blox, Skip button shows after 10 seconds 2- Added show folder size API

Added Folder size call and Skip
